# Useful links
# https://medium.com/swlh/how-to-deploy-your-application-to-digital-ocean-using-github-actions-and-save-up-on-ci-cd-costs-74b7315facc2
# https://codememoirs.com/automatic-deployment-digitalocean-github-actions
# https://stackoverflow.com/questions/69873818/how-to-git-pull-at-remote-server-and-then-recreate-the-env-file-using-github-act

name: Deploy to AWS

on:
  # run it on push to the develop repository branch
  push:
    branches: [develop]
    
  # run it during pull request
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install root dependencies
        run: npm install

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run tests
        run: npm test
        

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deploy application to DigitalOcean
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            export PATH=$PATH:/root/.nvm/versions/node/v20.10.0/bin
            cd dlta-capstone
            cd backend
            git checkout develop
            git pull
            cat <<EOF > .env
            DB_URI=${{ secrets.DB_URI }}
            PORT=${{ secrets.PORT }}
            EOF
            yarn install
            yarn reload